### ISSUE TITLE
7.8.0-ce doesn't load on Tomcat

### ISSUE THREAD

**Issue by johnmanko** [TIBCOSoftware/jasperreports-server-ce#15]
This is installed on a Tomcat Docker image version `tomcat:9.0.37-jdk11-openjdk`.  

This error has been [reported by many users over the year](https://community.jaspersoft.com/questions/822153/error-closing-context), with zero attention and zero resolution. 

How do I get past this?

```
07-Oct-2020 15:07:14.200 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/jasperserver]
07-Oct-2020 15:07:23.557 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-10-07T15:07:49,470 ERROR JNDIResourceProvider,main:75 - error closing context javax.naming.OperationNotSupportedException: Context is read only
	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:990)
	at org.apache.naming.NamingContext.close(NamingContext.java:759)
	at com.tonbeller.tbutils.res.JNDIResourceProvider.close(JNDIResourceProvider.java:72)
	at com.tonbeller.tbutils.res.CompositeResourceProvider.close(CompositeResourceProvider.java:56)
	at com.tonbeller.tbutils.res.ResourcesFactory.initialize(ResourcesFactory.java:163)
	at com.tonbeller.tbutils.res.ResourcesFactory.<init>(ResourcesFactory.java:92)
	at com.tonbeller.tbutils.res.ResourcesFactory.<clinit>(ResourcesFactory.java:89)
	at com.tonbeller.tbutils.res.ResourcesFactoryContextListener.contextInitialized(ResourcesFactoryContextListener.java:23)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1866)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)

07-Oct-2020 15:07:52.405 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/jasperserver] has finished in [38,202] ms
07-Oct-2020 15:07:52.411 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
07-Oct-2020 15:07:52.434 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio-8443"]
07-Oct-2020 15:07:52.446 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [38316] milliseconds
```

**Comment by johnmanko** [comment]
The package `com.tonbeller.tbutils.res` appears to be a very old library with [no maven presence](https://mvnrepository.com/search?q=com.tonbeller.tbutils.res).   According to the Jasper source, you seem to be using your own custom packaged version:

[jpivot-groupId:jpivot-artifactId:jpivot-version](https://github.com/TIBCOSoftware/jasperreports-server-ce/blob/f0b6143e3470aa4a48fe5cb2ffe4bfef6e5d3c90/pom.xml) and [usage](https://github.com/TIBCOSoftware/jasperreports-server-ce/search?q=jpivot-groupId):
```xml
    <jpivot-groupId>jaspersoft.ji-pro.ji-jpivot-ui</jpivot-groupId>
    <jpivot-artifactId>ji-jpivot</jpivot-artifactId>
    <jpivot-version>6.1.0</jpivot-version>
```

Where is the `ji-jpivot` source repository?  There isn't a maven artifact for it either.  If this is a pro-only library, why is it included in the ce edition?  Was this test on Tomcat's `tomcat:9.0.37-jdk11-openjdk` Docker image?  Is there additional configuration needed prior to deployment?

Come on guys.  Help us out here.

**Comment by johnmanko** [comment]
The last reference to the source I can find is [this](https://community.jaspersoft.com/questions/801245/ji-jpivot-source-code), which doesn't exist anymore.  Is JasperSfot in violation of an open source license by not publishing their `ji-jpivot` library source?
